### ISSUE TITLE
multi gpu support

### ISSUE THREAD

**Issue by seiyajin** [OLoKo64/upscale-rs#13]
can you add multi gpu support or gpu selector, for your next update, i think it will good performance and faster for upscaling image

**Comment by OLoKo64** [comment]
Nice suggestion. I'll be looking into it for the next update.

Currently I have a Linux machine with a integrated graphics and a Nvidia one, so I will be testing there.

I will be releasing rc builds when I manage to implement it, stay tuned.

**Comment by OLoKo64** [comment]
Hi, during my launch today I started the implementation of multi gpu support, follow this PR to see the progress: https://github.com/OLoKo64/upscale-rs/pull/12

I didn't had time to test it yet but it should be already working, as the correct arguments are being correctly passed to the binary that does the upscaling.

The UI needs a bit of work still.
![image](https://user-images.githubusercontent.com/49915167/221240655-c2ec3b39-0726-4cac-89cc-fe05c2d8eaf4.png)


The documentation of the commands can be found in this link: https://github.com/xinntao/Real-ESRGAN#usage-of-portable-executable-files

**Comment by seiyajin** [comment]
thanks alot for replying my request, this is will be great update

**Comment by OLoKo64** [comment]
@seiyajin I just released the first cross plataform release candidate for the `v0.2.2` which includes the advanced options for multi GPU as well as added support for `webp` images.

Give it a spin and tell me what you think.

**Comment by seiyajin** [comment]
thanks for rc build update, seem work ok, for my old GPU (gtx660 + gtx750ti)
![oneGPU](https://user-images.githubusercontent.com/38051847/221388082-fffe63ab-6817-445b-a9cb-88e5526db883.jpg)

but i think for some reason multiGPU string not worked so well (case happen when i'm using cupscale too)
![multiGPU](https://user-images.githubusercontent.com/38051847/221388154-17c515cc-55f2-4a54-976c-d9576259b3b5.jpg)
i think this problem happen from realESRGAN script, not pytorch modul

**Comment by OLoKo64** [comment]
Hey, thanks for testing so quickly.

So the selection of GPU is working but not the parallelization when using multi GPU.

I can think in 3 possibilities:
- Maybe you need to pass the other parameters as well, for example, when using `gpu-id: 0,1` set the `tile-size: 0,0` and the `load:proc:save: 1:2,1:2` as well. Can you try that? My notebook does not recognize the integrated graphics as a second GPU so I cant test it.
- The documentation was not clear to me if the multi GPU support works only when selecting a directory, not individual files, so the parallelization occurs that way. This is a bit of a problem as I designed the app to select files only, so you can select the ones you need, not folders. This would require a bit more work to get right.
- The last option is like you said, maybe is something wrong with the realESRGAN binary.

**Comment by seiyajin** [comment]
ok, i will try with other parameter, like you said parallelization multi
gpu seem complicated,  i tried searching solution about this problem, but i
can not find the right answer. by the way, can i make request, for next
update, can you add option for gfgan model inclued(optional), for face
restoration, thank you

**Comment by OLoKo64** [comment]
@seiyajin Some updates.

I tested some things to make the multi GPU work but sadly I was not successful, it really seems that it is made for when you select a folder, but as it would require a good chunk of work and it just split the work between the images, not really a multi GPU.

Two things make me not want to add the upscale per folder:
1. It's not certain that it will work in the end, as I researched and didn't find any thread saying that works as intended, taking account the work it would take just to test it, not worth it, at least for now.
2. In my experience with similar apps, per-folder upscaling was a bit hit and miss, if you selected a folder that contained anything other than photos they could crash, even worse, when you forgot some photos that were already upscaled in that folder, causing the application to create images larger than 1GB.

---

> by the way, can i make request, for next
update, can you add option for gfgan model inclued(optional), for face
restoration

In this app I'm using the binary, not the Python script, and it still has the feature ["Support face restore - GFPGAN"](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan#hourglass_flowing_sand-todo-list) as a TODO.

---

For now im going to finish this update including the following:
- Ability to select GPUs and it's advanced features, but will be removing the reference to multi GPU.
- Add the option of Test-Time Augmentation -  (TTA mode able to reduce several type of artifacts but it's 8x slower than non TTA mode).
- Add support for `.webp` images.
- And some other minor changes.


In the future if I manage to find a way to make the multi GPU work I will update it, same with the face restoration, as soon as they update it i will as well.
