### ISSUE TITLE
program wont open

### ISSUE THREAD

**Issue by TheShadowGamer06** [OLoKo64/upscale-rs#15]
just installed the latest version and as soon as I open it, it immediately closes
![Animation](https://github.com/OLoKo64/upscale-rs/assets/23390898/ff341147-0c92-424f-a0f3-93352d2e27df)

**Comment by OLoKo64** [comment]
Hi, Im going to investigate issue in this weekend

**Comment by oloko64** [comment]
I just released a new version with some updates, [version 0.2.3](https://github.com/OLoKo64/upscale-rs/releases/tag/v0.2.3). You can try it out to see if it works on your machine.

I tested on my VM and had a friend to test on a real machine, all working fine.

Feel free to add a comment if you still having problems.
