### ISSUE TITLE
Process one at a time?

### ISSUE THREAD

**Issue by jasonstetson** [OLoKo64/upscale-rs#6]
Process exited with non-zero exit code,
For more information run the app from a terminal and check
the output.
Or check the log file located at

I pull in 3 pictures and set it to work hmm but it looks like it's trying to upscale all the pictures at once 
can't you set it to process one at a time?

**Comment by OLoKo64** [comment]
Hi

It should already be processing one at a time.

What are your operating system? What GPU do you have? (You need a GPU to run this app)

If you can enable logs in the options and send the log report.

**Comment by OLoKo64** [comment]
Closing this issue due the lack of interaction.

If you continue to have this issue feel free to open it again.
